// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt20guh2_-l5G6wbJiFJczkkM6K5EbVjw',
    appId: '1:1071332753914:web:9b69cf89da0e88164b2443',
    messagingSenderId: '1071332753914',
    projectId: 'sentinelshq',
    authDomain: 'sentinelshq.firebaseapp.com',
    storageBucket: 'sentinelshq.firebasestorage.app',
    measurementId: 'G-PXFRNYNS1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGEylJY-WvoBNQrauu0m4dYi_iLjBVNY',
    appId: '1:1071332753914:android:46354c96f418adeb4b2443',
    messagingSenderId: '1071332753914',
    projectId: 'sentinelshq',
    storageBucket: 'sentinelshq.firebasestorage.app',
  );
}
